name = "bookmark-navigator-dev"
compatibility_date = "2024-01-01"
pages_build_output_dir = "./public"

# 生产环境D1数据库绑定
[[d1_databases]]
binding = "BOOKMARKS_DB"
database_name = "bookmark-navigator-dev-db"
database_id = "b13e1f46-d57c-48e5-a0ee-25c00ec49f03"

# 本地开发配置
[env.development]
compatibility_date = "2024-01-01"

# D1 数据库绑定（本地开发用）
[[env.development.d1_databases]]
binding = "BOOKMARKS_DB"
database_name = "bookmark-navigator-dev-db"
database_id = "b13e1f46-d57c-48e5-a0ee-25c00ec49f03"

# R2 存储桶绑定（可选，用于备份测试）
[[env.development.r2_buckets]]
binding = "BACKUP_BUCKET"
bucket_name = "bookmark-backups-local"

# 环境变量（可选）
[env.development.vars]
NODE_ENV = "development"
# JWT_SECRET = "your-dev-jwt-secret"
# ADMIN_PASSWORD = "admin123"